# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: mkdir $HOME/go
  displayName: TestInvok
- script: sudo apt-get install docker
  displayName: Docker
- script: sudo apt-get install git
  displayName: Git
- script: hack/env hack/build-base-images.sh
  displayName: Build
- script: hack/env make release

- script: |
  displayName: 'Do not run a multi-line script that will fail'
